default_provider = "age"

[providers.age]
type = "age"
recipients = [
    "age12quth6r6uqc79s9uwrnn7pkfkvnectl29k7v2et8jmvqf37kxglst2vj4n",
    "age1yubikey1qgmfypn3j57jmv9794emva0nn4d4py337h6lcecuuhklzhdmuhl5vt7q6z5"
]

[secrets]
GITLAB_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcDhybWFzb0xoWmNWRGpWb09aUm5MVktlZ0lHV0hvOW4vOXd2WFJ1RlRRCkJxNjlDUW82cTNKNHJyUUFsTkx6MTZnUkQ3Q3lNYlJBQlhabnFmRHBpcEEKLT4gdX0jLWdyZWFzZQpUZWVKV2pjYlE1SHZXcXRsa1czYU5jNG4rbkZmMTBjc3Vqdkd1V0lLYVRTcG0yMkxycGE4T0NLZTNTa0JTT2gxCm42NTRpR1JKUHR4NFVEaWlrNEpXVmg2QVZDNW95c1paZ2NzCi0tLSBDQ2pPOTYxOVBaMVRJQkljOVUzYUdBeDlMWlBwVXpsaGRWK25Yb0QyM1lrCgzPlxau+60eU5bIK382zHoS9x5MQbLWKEf6tGtEvNFjh5gjGFZwtXFLxs1aw03luS63E5H5p+FQQXdWEM9734wpwqhaaPMT7Wf02Z3ucrTNjCUvvhbT4s80IZ1/hut6p9DLaD3SajDH+VUgEjuz9eddLng5VUmiIIP7guR8" }
