.local/bin/mise:
  type: file
  url: https://github.com/jdx/mise/releases/download/v2024.2.13/mise-v2024.2.13-linux-x64
  executable: true
.local/bin/gopass-jsonapi:
  type: archive-file
  url: https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.15.11/gopass-jsonapi-1.15.11-linux-amd64.tar.gz
  executable: true
  path: gopass-jsonapi
.local/share/fonts/NerdFonts/FiraCode:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.tar.xz
  include:
  - 'FiraCodeNerdFont-*.ttf'
.local/share/fonts/NerdFonts/JetBrainsMono:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.tar.xz
  include:
  - 'JetBrainsMonoNerdFont-*.ttf'
.local/share/fonts/NerdFonts/SourceCodePro:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/SourceCodePro.tar.xz
  include:
  - '*.ttf'
.local/share/gopass/stores/root:
  type: git-repo
  url: git@github.com:joke/gopass.git
