.local/bin/rtx:
  type: file
  url: https://github.com/jdxcode/rtx/releases/download/v1.25.4/rtx-v1.25.4-linux-x64
  refreshPeriod: 168h
  executable: true
.local/share/dracula/konsole:
  type: git-repo
  url: git@github.com:dracula/konsole.git
.local/share/gopass/stores/root:
  type: git-repo
  url: git@github.com:joke/gopass.git
.local/share/fonts/NerdFonts/JetBrainsMono:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/JetBrainsMono.zip
  exclude:
    - '*Windows Compatible*'
    - '*Complete Mono*'
.local/share/fonts/NerdFonts/SourceCodePro:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/SourceCodePro.zip
  exclude:
    - '*Windows Compatible*'
    - '*Complete Mono*'
.local/share/fonts/NotoColorEmoji:
  type: archive
  url: 'https://fonts.google.com/download?family=Noto%20Color%20Emoji'
