[settings]
experimental = true
not_found_auto_install = true
disable_default_registry = true
trusted_config_paths = [
  '~/Projects/joke'
]
disable_backends = [
  "asdf"
]

[tools]
"aqua:aws/aws-cli" = "2.27.53"
"aqua:hashicorp/terraform" = "1.12.2"
"aqua:helm/helm" = "3.18.4"
"aqua:kubectl" = "1.33.3"
"aqua:pre-commit" = "4.2.0"
"ubi:GoogleContainerTools/skaffold" = "2.16.1"
"ubi:age-sops/age" = "1.90.1"
"ubi:aquaproj/aqua" = "2.53.4"
"ubi:buildpacks-community/kpack-cli" = "0.13.0"
"ubi:buildpacks/pack" = "0.38.2"
"ubi:cli/cli" = { version = "2.75.1", exe = "gh" }
"ubi:derailed/k9s" = "0.50.9"
"ubi:deviceinsight/kafkactl" = "5.11.0"
"ubi:ducaale/xh" = "0.24.1"
"ubi:getsops/sops" = "3.10.2"
"ubi:gleam-lang/gleam" = "1.11.1"
"ubi:gopasspw/gopass" = "1.15.16"
"ubi:gopasspw/gopass-jsonapi" = "1.15.16"
"ubi:grafana/k6" = "1.1.0"
"ubi:grafana/mimir" = { version = "mimir-2.15.0", exe = "mimirtool", matching = "mimirtool" }
"ubi:gruntwork-io/terragrunt" = "0.83.2"
"ubi:houseabsolute/ubi" = "0.7.2"
"ubi:istio/istio" = { version = "1.26.2", exe = "istioctl" }
"ubi:JanDeDobbeleer/oh-my-posh" = "26.16.0"
"ubi:jdx/mise" = "2025.7.11"
"ubi:jdx/usage" = "2.2.2"
"ubi:junegunn/fzf" = "0.64.0"
"ubi:knative-extensions/kn-plugin-admin" = "knative-v1.17.0"
"ubi:knative-extensions/kn-plugin-event" = "knative-v1.17.0"
"ubi:knative-extensions/kn-plugin-service-log" = "knative-v1.1.0"
"ubi:knative-extensions/kn-plugin-source-kafka" = "knative-v1.17.0"
"ubi:knative/client" = { version = "knative-v1.17.0", rename_exe = "kn" }
"ubi:kubernetes/minikube" = "1.36.0"
"ubi:mikefarah/yq" = "4.46.1"
"ubi:minamijoyo/tfupdate" = "0.9.1"
"ubi:mk-5/fjira" = "1.4.4"
"ubi:mvdan/sh" = "3.12.0"
"ubi:patrickdappollonio/kubectl-slice" = "1.4.2"
"ubi:sbstp/kubie" = "0.26.0"
"ubi:starship/starship" = "1.23.0"
"ubi:str4d/age-plugin-yubikey" = "0.5.0"
"ubi:str4d/rage" = "0.11.1"
"ubi:synfinatic/aws-sso-cli" = "2.0.3"
"ubi:terraform-docs/terraform-docs" = "0.20.0"
"ubi:terraform-linters/tflint" = "0.58.1"
"ubi:turbot/steampipe" = "2.1.0"
"ubi:twpayne/chezmoi" = "2.63.0"
"ubi:wagoodman/dive" = "0.13.1"
"ubi:zimfw/zimfw" = { version = "1.18.0", rename_exec = "zimfw.zsh" }
java = "oracle-graalvm-24.0.2"
