[settings]
experimental = true
not_found_auto_install = true
trusted_config_paths = [
    '~/Projects/joke'
]

[plugins]
sops = 'https://github.com/feniix/asdf-sops'

[tools]
age = '1.1.1'
age-plugin-yubikey = '0.4.0'
apko = '0.17.0'
asciidoctorj = '2.5.10'
awscli = '2.13.3'
chezmoi = '2.52.4'
cosign = '2.2.3'
dive = '0.10.0'
elixir = '1.16.2-otp-26'
erlang = '26.2.3'
fzf = '0.37.0'
github-cli = '2.22.1'
glab = '1.34.0'
gleam = '1.0.0'
go = '1.21.6'
gomplate = 'v3.11.5'
gopass = '1.15.14'
groovy = '4.0.10'
helm = '3.16.2'
istioctl = '1.23.2'
java = 'temurin-21.0.0+35.0.LTS'
k6 = '0.54.0'
k9s = '0.26.7'
kafkactl = '5.0.6'
kn = '1.15.0'
krew = '0.4.3'
kubectl = '1.30.0'
kubie = '0.24.0'
loki-logcli = '3.0.0'
maven = '3.8.7'
mimirtool = '2.11.0'
minikube = '1.32.0'
node = 'lts'
pre-commit = '4.0.1'
shfmt = '3.7.0'
skaffold = '2.13.2'
sops = '3.9.1'
starship = '1.21.1'
steampipe = '0.24.2'
terraform = '1.9.8'
terraform-docs = '0.16.0'
terragrunt = '0.68.4'
tflint = '0.47.0'
tfupdate = '0.7.2'
xh = '0.23.0'
yq = '4.44.3'
