[settings]
experimental = true
not_found_auto_install = true
disable_default_registry = true
trusted_config_paths = [
  '~/Projects/joke'
]
disable_backends = [
  "asdf"
]

[tools]

"github:jdx/mise" = "2025.8.20"
"github:jdx/usage" = "2.2.2"
"github:junegunn/fzf" = "0.64.0"
"github:starship/starship" = "1.23.0"
"github:twpayne/chezmoi" = "2.63.0"
"github:zimfw/zimfw" = { version = "1.18.0", asset_pattern = "zimfw.zsh", bin = "zimfw.zsh" }

"npm:ergogen" = "latest"
