[settings]
experimental = true
trusted_config_paths = [
    '~/Projects/joke'
]

[tools]
age = '1.1.1'
age-plugin-yubikey = '0.4.0'
asciidoctorj = '2.5.10'
awscli = '2.13.3'
chezmoi = '2.42.3'
cosign = '2.2.3'
dive = '0.10.0'
elixir = '1.16.2-otp-26'
erlang = '26.2.3'
fzf = '0.37.0'
github-cli = '2.22.1'
glab = '1.34.0'
gleam = '1.0.0'
go = '1.21.6'
gomplate = 'v3.11.5'
gopass = '1.15.5'
groovy = '4.0.10'
helm = '3.14.2'
istioctl = '1.19.0'
java = 'temurin-21.0.0+35.0.LTS'
k6 = '0.47.0'
k9s = '0.26.7'
kafkactl = '5.0.6'
kn = '1.12.0'
krew = '0.4.3'
kubectl = '1.30.0'
kubie = '0.22.0'
loki-logcli = '3.0.0'
maven = '3.8.7'
mimirtool = '2.11.0'
minikube = '1.32.0'
node = 'lts'
pre-commit = '3.3.3'
shfmt = '3.7.0'
skaffold = '2.10.0'
sops = '3.8.1'
starship = '1.20.1'
steampipe = '0.18.4'
terraform = '1.9.0'
terraform-docs = '0.16.0'
terragrunt = '0.59.4'
tflint = '0.47.0'
tfupdate = '0.7.2'
xh = '0.22.2'
yq = '4.35.1'
