[settings]
trusted_config_paths = [
    '~/Projects/joke'
]
experimental = true

[tools]
age = '1.1.1'
age-plugin-yubikey = '0.4.0'
asciidoctorj = '2.5.10'
awscli = '2.13.3'
chezmoi = '2.42.3'
dive = '0.10.0'
fzf = '0.37.0'
github-cli = '2.22.1'
glab = '1.34.0'
gopass = '1.15.5'
gomplate = 'v3.11.5'
groovy = '4.0.10'
helm = '3.13.2'
istioctl = '1.19.0'
java = 'temurin-21.0.0+35.0.LTS'
k6 = '0.47.0'
k9s = '0.26.7'
kafkactl = '3.0.3'
kn = '1.11.0'
krew = '0.4.3'
kubectl = '1.27.0'
kubie = '0.22.0'
maven = '3.8.7'
minikube = '1.32.0'
node = 'lts'
pre-commit = '3.3.3'
skaffold = '2.9.0'
sops = '3.8.1'
starship = '1.16.0'
shfmt = '3.7.0'
steampipe = '0.18.4'
terraform = '1.6.3'
terraform-docs = '0.16.0'
terragrunt = '0.53.1'
tflint = '0.47.0'
tfupdate = '0.7.2'
xh = '0.17.0'
yq = '4.35.1'
