[settings]
missing_runtime_behavior = 'autoinstall'

trusted_config_paths = [
    '~/Projects/joke'
]

[tools]
age = '1.1.1'
asciidoctorj = '2.5.10'
awscli = '2.9.21'
chezmoi = '2.35.0'
dive = '0.10.0'
fzf = '0.37.0'
github-cli = '2.22.1'
glab = '1.25.3'
gopass = '1.15.5'
groovy = '4.0.10'
helm = '3.12.1'
istioctl = '1.16.2'
java = 'temurin-17.0.6+10'
k9s = '0.26.7'
kafkactl = '3.0.3'
kn = '1.9.0'
krew = '0.4.3'
kubectl = '1.26.0'
kubie = '0.19.3'
maven = '3.8.7'
minikube = '1.29.0'
node = 'lts'
pre-commit = '3.0.4'
skaffold = '2.1.0'
sops = '3.7.3'
starship = '1.15.0'
steampipe = '0.18.4'
terraform = '1.5.2'
terraform-docs = '0.16.0'
terragrunt = '0.48.0'
tflint = '0.47.0'
tfupdate = '0.6.8'
xh = '0.17.0'
yq = '4.34.1'
