[settings]
missing_runtime_behavior = 'autoinstall'

trusted_config_paths = [
    '~/Projects/joke'
]

[plugins]
age-plugin-yubikey = 'https://github.com/joke/asdf-age-plugin-yubikey'

[tools]
age = '1.1.1'
age-plugin-yubikey = '0.4.0'
asciidoctorj = '2.5.10'
awscli = '2.13.3'
chezmoi = '2.35.0'
dive = '0.10.0'
fzf = '0.37.0'
github-cli = '2.22.1'
glab = '1.25.3'
gopass = '1.15.5'
groovy = '4.0.10'
helm = '3.12.2'
istioctl = '1.18.2'
java = 'temurin-17.0.6+10'
k9s = '0.26.7'
kafkactl = '3.0.3'
kn = '1.9.0'
krew = '0.4.3'
kubectl = '1.27.0'
kubie = '0.21.1'
maven = '3.8.7'
minikube = '1.29.0'
node = 'lts'
pre-commit = '3.3.3'
skaffold = '2.1.0'
sops = '3.7.3'
starship = '1.15.0'
shfmt = '3.7.0'
steampipe = '0.18.4'
terraform = '1.5.3'
terraform-docs = '0.16.0'
terragrunt = '0.48.6'
tflint = '0.47.0'
tfupdate = '0.7.2'
xh = '0.17.0'
yq = '4.34.1'
